### PR TITLE
Support for TinyLlama-1.1b

### PR DESCRIPTION
**Pull request by acalatrava**
TinyLlama-1.1B is a 1.1B llama model that's being trained on 3 trillion tokens. Since it's a very small model it will run on almost any device which make it very suitable for MLC-LLM.
https://github.com/jzhang38/TinyLlama

They published a checkpoint version with 500B parameters trained and fine-tuned to chat, which I converted to MLC-LLM format:
https://huggingface.co/acalatrava/mlc-chat-TinyLlama-1.1B-Chat-v0.2-q4f16_1

I also created a fine-tuned version and converted to MLC-LLM using the orca dataset.
https://huggingface.co/acalatrava/mlc-chat-TinyLlama-1.1B-orca-gpt4-q4f16_1

### CODE REVIEW

**Comment by CharlieFRuan** [comment]
Thank you so much for contributing!

**Comment by DavidGOrtega** [comment]
@acalatrava I have a finetuned tinyllama however I have to build the wasm. Did you created it or did you use other llama wasm?

**Comment by CharlieFRuan** [comment]
Hi @DavidGOrtega, I just added this; please see https://github.com/mlc-ai/binary-mlc-llm-libs/pull/77. This is also included in web-llm's `simple-chat` as you can see TinyLlama from the demo https://webllm.mlc.ai/

**Comment by CharlieFRuan** [comment]
Hmm are you following the new workflow `mlc_chat compile`? I am guessing you are using the old `build.py`. See more here: https://llm.mlc.ai/docs/compilation/compile_models.html

Or the end-to-end doc for web-llm: https://llm.mlc.ai/docs/deploy/javascript.html

**Comment by CharlieFRuan** [comment]
For context, we recently had a revamp of the compilation flow

**Comment by DavidGOrtega** [comment]
@CharlieFRuan as I [stated here](https://github.com/mlc-ai/mlc-llm/issues/1616) Its mean to be that Im using the latest

```
pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly mlc-ai-nightly
```

Im having also an issue with my converted model

```
Check failed: (func.defined()) is false: Error: Cannot find PackedFunc vm.builtin.paged_attention_kv_cache_attention in either Relax VM kernel library, or in TVM runtime PackedFunc registry, or in global Relax functions of the VM executable
```

Im thinking that I might have an old TVM relax version

**Comment by DavidGOrtega** [comment]
Using yours I also have a problem

```
ValueError: Cannot find parameter in cache: model.embed_tokens.weight
```

**Pull request merged**
