### PR TITLE
Update Android Apk linked in docs

### PR DESCRIPTION
**Pull request by Kartik14**
This PR updates the android apk

### CODE REVIEW

**Comment by asl97** [comment]
Is it intented that this update conflict with past version?
Screenshot_2023-12-31-03-08-39-263_com google android packageinstaller

and the fact that to update require uninstalling which would delete exisiting models and require redownloading them?

**Comment by Kartik14** [comment]
@asl97 Yes unfortunately. Although you can move the weights to a temp dir before uninstalling and then move it back after reinstalling. You can refer [here](https://llm.mlc.ai/docs/deploy/android.html#id5) for more details.

**Comment by Sxela** [comment]
Hm. The option to add models via the app interface was removed?

**Comment by asl97** [comment]
> Hm. The option to add models via the app interface was removed?

Quote from https://github.com/mlc-ai/mlc-llm/pull/1494
> Remove add model by url from android app since it causes confusion

As far as I am aware, it has never worked. and I assume that what they mean by confusion.

**Comment by Kartik14** [comment]
> Hm. The option to add models via the app interface was removed?

It worked but only for models under `https://huggingface.co/mlc-ai` which led to some confusion. We will make it easier to add new models using a different interface.

**Comment by Thore1954** [comment]
Llama-2 is now broken on Pixel 7. It says Ready to chat but when I send a prompt it crashes after 30 secs.

**Pull request merged**
