### PR TITLE
Add support for quantized qwen2-0.5b

### PR DESCRIPTION
**Pull request by bil-ash**
Add support for quantized(q4f16) qwen2-0.5b . Wasm library taken from https://huggingface.co/julientfai/Qwen2-0.5B-Instruct-q4f16_1-Opilot/resolve/main/Qwen2-0.5B-Instruct-q4f16_1-webgpu.wasm?download=true

### CODE REVIEW

**Comment by Neet-Nestor** [comment]
Related PRs:
- https://github.com/mlc-ai/web-llm/pull/490
- https://github.com/mlc-ai/web-llm-chat/pull/44
- https://github.com/mlc-ai/binary-mlc-llm-libs/pull/128

**Review by CharlieFRuan — COMMENTED** [review]
Took a look, this model is compiled with prefill chunk size 2k. Could you change the file name to `Qwen2-0.5B-Instruct-q4f16_1-ctx4k_cs2k-webgpu.wasm`? Thanks!

**Comment by bil-ash** [comment]
I have renamed as suggested. By the way, what is prefill chunk size and how does it relate to memory usage and performance?

**Comment by CharlieFRuan** [comment]
Thanks! Say prefill chunk size is 2k, if a prompt is 4k, it will be prefilled twice instead of all at once. This helps reduce the size of the intermediate buffer for the matrix multiplication.

**Pull request merged**
